app_mode: "dev"
database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "1164657389abc"
  dbname: "moxin-zhicheng"

redis:
  host: "127.0.0.1"
  port: "6422"
  password: "1164657389abc" # 如果本地没设置密码就留空
  db: 0        # 默认数据库